# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'LeafBank' do
	
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
	inhibit_all_warnings!
	# Pods for LeafBank
	
	pod 'Sluthware', :git => 'https://patsluth@bitbucket.org/patsluth/sluthware-swift.git'
	pod 'R.swift'
	pod 'SegueManager'
	pod 'SegueManager/R.swift'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Firebase'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Firestore'
	pod 'RxSwiftExt'
	pod 'RxFirebaseAuth'
	pod 'RxFirebase/Auth'
	pod 'RxFirebase/Firestore'
	pod 'RxEureka'
	pod 'PromiseKit'
	pod 'Alertift'
	pod 'Eureka'
    pod 'BoringSSL'
    pod 'ResearchKit'
	
end





post_install do |installer_representation|
	installer_representation.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
			config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
			config.build_settings['ENABLE_BITCODE'] = 'NO'
			config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
			
			if config.name == 'Release'
				config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
			end
			
			if target.name == 'R.swift.Library'
				config.build_settings['SWIFT_VERSION'] = '4.0s'
			end
		end
	end
end

